# Generated by Django 3.1 on 2020-09-01 09:25

import backup.models
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Setting Name')),
                ('type', models.CharField(choices=[('Boolean', 'Boolean'), ('String', 'String'), ('Number', 'Number')], default='Boolean', max_length=10, verbose_name='Setting Type')),
                ('bool_setting', models.BooleanField(default=False, verbose_name='Setting Value (Boolean)')),
                ('string_setting', models.CharField(blank=True, max_length=64, null=True, verbose_name='Setting Value (String)')),
                ('float_setting', models.FloatField(blank=True, null=True, verbose_name='Setting Value (Number)')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Setting Description')),
            ],
            options={
                'verbose_name': 'App Setting',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=32)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('password', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('active', models.BooleanField(default=False)),
                ('backup_daily', models.BooleanField(default=False)),
                ('condense_weekly', models.BooleanField(default=False)),
                ('condense_monthly', models.BooleanField(default=False)),
                ('condense_yearly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('database_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='backup.databasetype')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='backup.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='db_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.databasetype', verbose_name='Database Type'),
        ),
        migrations.CreateModel(
            name='BackupEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=backup.models.backup_path)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('added_on_time', models.TimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=16, null=True)),
                ('do_not_delete', models.BooleanField(default=False)),
                ('safe_deleted', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='backup.campaign')),
            ],
        ),
    ]
