# Generated by Django 3.0.8 on 2020-07-30 22:41

import backup.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Setting Name')),
                ('type', models.CharField(choices=[('Boolean', 'Boolean'), ('String', 'String'), ('Number', 'Number')], default='Boolean', max_length=10, verbose_name='Setting Type')),
                ('bool_setting', models.BooleanField(default=False, verbose_name='Setting Value (Boolean)')),
                ('string_setting', models.CharField(blank=True, max_length=64, null=True, verbose_name='Setting Value (String)')),
                ('float_setting', models.FloatField(blank=True, null=True, verbose_name='Setting Value (Number)')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Setting Description')),
            ],
            options={
                'verbose_name': 'App Setting',
            },
        ),
        migrations.CreateModel(
            name='DatabaseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=32)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('db_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.DatabaseTypes')),
            ],
        ),
        migrations.CreateModel(
            name='BackupEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=backup.models.backup_path)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.Campaign')),
            ],
        ),
    ]
