# Generated by Django 3.0.8 on 2020-07-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_auto_20200731_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='backup_monthly',
            new_name='condense_monthly',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='backup_weekly',
            new_name='condense_weekly',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='backup_yearly',
            new_name='condense_yearly',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='condense_backups',
        ),
    ]
