# Generated by Django 3.0.8 on 2020-07-31 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_auto_20200731_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupentry',
            name='added_on_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupentry',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
