# Generated by Django 3.0.8 on 2020-07-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_backupentry_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupentry',
            old_name='save',
            new_name='do_not_delete',
        ),
    ]
