# Generated by Django 3.0.8 on 2020-07-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0007_auto_20200731_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupentry',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='backup.Campaign'),
        ),
    ]
