# Generated by Django 3.0.8 on 2020-07-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0008_auto_20200731_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupentry',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='db_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.DatabaseTypes', verbose_name='Database Type'),
        ),
    ]
