# Generated by Django 3.0.8 on 2020-07-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0009_auto_20200731_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupentry',
            name='file_size',
        ),
    ]
