# Generated by Django 3.0.8 on 2020-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_remove_backupentry_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupentry',
            name='source',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
