# Generated by Django 3.1 on 2020-08-13 08:14

from django.db import migrations, models
import django_cryptography.fields

from backup.models import Campaign





class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0012_auto_20200813_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
