# Generated by Django 3.1 on 2020-08-13 08:16

from django.db import migrations

from backup.models import Campaign





class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0013_campaign_password'),
    ]

    operations = [
        # migrations.RunPython(move_passwords),
        migrations.RemoveField(
            model_name='campaign',
            name='old_password',
        ),
    ]
