# Generated by Django 3.1 on 2020-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0014_remove_campaign_old_password'),
    ]

    operations = [

    ]
