# Generated by Django 3.1 on 2020-08-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0015_campaign_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155)),
                ('value', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.campaign')),
            ],
        ),
    ]
