# Generated by Django 3.1 on 2020-08-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0016_campaignfields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabaseTypes',
            new_name='DatabaseType',
        ),
    ]
