# Generated by Django 3.1 on 2020-08-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0017_auto_20200813_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('database_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.databasetype')),
            ],
        ),
        migrations.DeleteModel(
            name='CampaignFields',
        ),
    ]
