# Generated by Django 3.1 on 2020-08-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0018_auto_20200813_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfield',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='backup.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignfield',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignfieldoption',
            name='database_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='backup.databasetype'),
        ),
    ]
