# Generated by Django 3.1 on 2020-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0019_auto_20200813_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupentry',
            name='safe_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
