# Generated by Django 3.1 on 2020-08-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0021_testentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestEntry',
        ),
    ]
